FORMAT: 1A

# GraphQL API

This API demonstrates how to describe and test a GraphQL endpoint in Apiary.

See <http://graphql.org/docs/getting-started/> for details on GraphQL.

## GraphQL [/graphql{?query}]
- Parameters
    - query:`{ user(id: "1") { name } }` (string, required) - The QraphQL query string.

### Run Query [GET]

- Response 200 (application/json; charset=utf-8)

        {
          "data": {
            "user": {
              "name": "Dan"
            }
          }
        }
